# -*- coding: utf-8 -*-
"""Copy of RNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syuEMajKaQjqWUSPVlJFCRVHDWLD3MZJ

# Recurrent Neural Network

##Data Preprocessing

### Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""### Importing the training set"""

dataset_train = pd.read_csv('BTC.csv')
#training_set = dataset_train.iloc[:3000, 1:2].values

training_set = dataset_train.iloc[:3000, 2:3].values

"""### Feature Scaling"""

from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)

"""### Creating a data structure with 90 timesteps and 1 output"""

X_train = []
y_train = []
for i in range(90, 3000):
    X_train.append(training_set_scaled[i-90:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)

"""### Reshaping"""

X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

X_train.shape

"""##Building and Training the RNN

### Importing the Keras libraries and packages
"""

from keras.models import Sequential
from keras.layers import Dense, SimpleRNN
from keras.layers import LSTM
from keras.layers import Dropout

my_rnn_model = Sequential()
my_rnn_model.add(SimpleRNN(32, return_sequences=True))
#my_rnn_model.add(SimpleRNN(32, return_sequences=True))
#my_rnn_model.add(SimpleRNN(32, return_sequences=True))
my_rnn_model.add(SimpleRNN(32))
my_rnn_model.add(Dense(1)) # The time step of the output

my_rnn_model.compile(optimizer='rmsprop', loss='mean_squared_error')

# fit the RNN model
my_rnn_model.fit(X_train, y_train, epochs=100, batch_size=150, verbose=0)

"""##Making the predictions and visualising the results

### Price Prediction
"""

#real_stock_price = dataset_train.iloc[3001:, 1:2].values

real_stock_price = dataset_train.iloc[3001:, 2:3].values

"""### Getting the predicted price"""

#dataset_total = dataset_train['Open']
dataset_total = dataset_train['Close']
inputs = dataset_total[len(dataset_total) - len(real_stock_price) - 90:].values
inputs = inputs.reshape(-1,1)
inputs = sc.transform(inputs)
X_test = []
for i in range(90, len(inputs)):
    X_test.append(inputs[i-90:i, 0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
predicted_stock_price = my_rnn_model.predict(X_test)
predicted_stock_price = sc.inverse_transform(predicted_stock_price)

"""### Visualising the results"""

plt.style.use('fivethirtyeight')
plt.plot(real_stock_price, color = 'red', label = 'Real btc price')
plt.plot(predicted_stock_price, color = 'blue', label = 'Predicted Price')
plt.title('Price Prediction')
plt.xlabel('Time')
plt.ylabel('Price')
plt.legend()
plt.show()

from sklearn.metrics import r2_score
r2_score(real_stock_price,predicted_stock_price)

mse = my_rnn_model.evaluate(X_test, sc.transform(real_stock_price))
print('Mean Squared Error:', mse)

"""### Trying for a generalised value"""

#date='2014-12-24'
date='2023-03-05'
locate=int(np.where(dataset_train["Date"]==date)[0])
print(locate)

#l=dataset_train.iloc[locate-90:locate,1:2].values
l=dataset_train.iloc[locate-90:locate, 2:3].values
l=sc.transform(l)
print(l)

l=l.flatten()

l=l.reshape((1,90,1))

predict=my_rnn_model.predict(l)

print(sc.inverse_transform(predict))

#dataset_train.loc[locate+1]['Open']

dataset_train.loc[locate+1]['Close']