# -*- coding: utf-8 -*-
"""GUI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awIVPc2A3WW-ANkYW-ZkryS61em6Spm6
"""

!pip install yfinance
!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import yfinance as yf
# from datetime import date,timedelta
# from keras.models import load_model
# from PIL import Image
# 
# START = "2014-09-17"
# TODAY = date.today().strftime("%Y-%m-%d")
# df = yf.download('BTC-USD', START, TODAY)
# 
# s=date.today()
# s=s-timedelta(days=90)
# start=s.strftime("%Y-%m-%d")
# end=date.today().strftime("%Y-%m-%d")
# df1=yf.download("BTC-USD",start,end)
# 
# st.title('Bitcoin Price Prediction')
# st.write('(BTC-USD)')
# l=df1.loc[df1.index[-1]]['Close']
# 
# html_str = f"""
# <style>
# p.big-font {{
#   font: bold 50px Courier;
# }}
# </style>
# <p class="big-font">{l}</p>
# """
# st.markdown(html_str, unsafe_allow_html=True)
# 
# image = Image.open('btcn.jpg')
# new_image = image.resize((900, 300))
# st.image(new_image)
# 
# st.header("Bitcoin price Chart")
# st.dataframe(df1, width=1000, height=250)
# 
# 
# from sklearn.preprocessing import MinMaxScaler
# training_set=df.iloc[:3000, 4:5].values
# sc = MinMaxScaler(feature_range = (0, 1))
# training_set_scaled = sc.fit_transform(training_set)
# 
# model=load_model('trained_rnn.h5')
# l=df1.iloc[:, 4:5].values
# l=sc.transform(l)
# l=l.reshape((1,90,1))
# predict=model.predict([l])
# 
# st.header("Bitcoin price Graph")
# st.line_chart(df['Close'])
# 
# if st.button('Predict'):
#     l=float((sc.inverse_transform(predict)).flatten())
#     html_str1 = f"""
#     <style>
#     p.big-font1 {{
#       font: bold 50px Courier;
#       }}
#     </style>
#     <p class="big-font1">{l}</p>  
#     """
#     st.markdown(html_str1, unsafe_allow_html=True)
# 
#

!streamlit run app.py & npx localtunnel --port 8501

import yfinance as yf
from datetime import date,timedelta

START = "2014-09-17"
TODAY = date.today().strftime("%Y-%m-%d")
df = yf.download('BTC-USD', START, TODAY)
s=date.today()
s=s-timedelta(days=90)
print(s)

s=date.today()
s=s-timedelta(days=90)
start=s.strftime("%Y-%m-%d")
end=date.today().strftime("%Y-%m-%d")
df=yf.download("BTC-USD",start,end)
df