# -*- coding: utf-8 -*-
"""LSTM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RLMhPQPNDh2LQQDk5MeurZtSzMAechuc

### LSTM

##Data Preprocessing

### Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""### Importing the training set"""

dataset_train = pd.read_csv('BTC.csv')
training_set = dataset_train.iloc[:3000, 4:5].values

"""### Feature Scaling"""

from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)

"""### Creating a data structure with 90 timesteps and 1 output"""

X_train = []
y_train = []
for i in range(90, 3000):
    X_train.append(training_set_scaled[i-90:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)

"""### Reshaping"""

X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

"""##Building and Training the LSTM

### Importing the Keras libraries and packages
"""

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

"""### Initialising the LSTM"""

regressor = Sequential()

"""### Adding the first LSTM layer and some Dropout regularisation"""

regressor.add(LSTM(units = 80, return_sequences = True, input_shape = (X_train.shape[1], 1)))
regressor.add(Dropout(0.2))

"""### Adding a second LSTM layer and some Dropout regularisation"""

regressor.add(LSTM(units = 80, return_sequences = True))
regressor.add(Dropout(0.2))

"""### Adding a third LSTM layer and some Dropout regularisation"""

regressor.add(LSTM(units = 80, return_sequences = True))
regressor.add(Dropout(0.2))

"""### Adding a fourth LSTM layer and some Dropout regularisation"""

regressor.add(LSTM(units = 80))
regressor.add(Dropout(0.2))

"""### Adding the output layer"""

regressor.add(Dense(units = 1))

"""### Compiling the LSTM"""

regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

"""### Fitting the LSTM to the Training set"""

regressor.fit(X_train, y_train, epochs = 14, batch_size = 32)

regressor.save('trained_lstm.h5')

"""##Making the predictions and visualising the results

### **Price Prediction**
"""

#real_stock_price = dataset_train.iloc[3001:, 1:2].values
real_stock_price = dataset_train.iloc[3001:, 4:5].values

"""### Getting the predicted price"""

dataset_total = dataset_train['Close']
inputs = dataset_total[len(dataset_total) - len(real_stock_price) - 90:].values
inputs = inputs.reshape(-1,1)
inputs = sc.transform(inputs)
X_test = []
for i in range(90, len(inputs)):
    X_test.append(inputs[i-90:i, 0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
predicted_stock_price = regressor.predict(X_test)
predicted_stock_price = sc.inverse_transform(predicted_stock_price)

real_stock_price

predicted_stock_price

"""### Visualising the results"""

plt.style.use('fivethirtyeight')
plt.plot(real_stock_price, color = 'red', label = 'Real btc price')
plt.plot(predicted_stock_price, color = 'blue', label = 'Predicted Price')
plt.title('Price Prediction')
plt.xlabel('Time')
plt.ylabel('Price')
plt.legend()
plt.show()

from sklearn.metrics import r2_score
r2_score(real_stock_price,predicted_stock_price)

"""### Trying for a generalised value"""

date='2018-04-18'
locate=int(np.where(dataset_train["Date"]==date)[0])
print(locate)

#l=dataset_train.iloc[locate-90:locate,1:2].values
l=dataset_train.iloc[locate-90:locate, 4:5].values
l=sc.transform(l)
print(l)

l=l.flatten()

l=l.reshape((1,90,1))

predict=regressor.predict([l])

print(sc.inverse_transform(predict))

#dataset_train.loc[locate+1]['Open']

dataset_train.loc[locate+1]['Close']

from keras.models import load_model

model = load_model('trained_lstm.h5')
predicted = model.predict([l])

print(sc.inverse_transform(predicted))

from keras.models import load_model

model = load_model('trained_lstm.h5')

dataset_total = dataset_train['Close']
inputs = dataset_total[len(dataset_total) - len(real_stock_price) - 90:].values
inputs = inputs.reshape(-1,1)
inputs = sc.transform(inputs)
X_test = []
for i in range(90, len(inputs)):
    X_test.append(inputs[i-90:i, 0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
predicted_stock_price = model.predict(X_test)
predicted_stock_price = sc.inverse_transform(predicted_stock_price)

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error

print("Test RMSE: %.3f" % np.sqrt(mean_squared_error(real_stock_price, predicted_stock_price)))
print("Test MAPE: %.3f" % mean_absolute_percentage_error(real_stock_price, predicted_stock_price))

from sklearn.metrics import r2_score
r2_score(real_stock_price,predicted_stock_price)